;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	org-beginning-of-line
	))

(setq mc/cmds-to-run-once
      '(
	org-kill-line
	org-self-insert-command
	org-time-stamp
	))
